### ISSUE TITLE
USER STORY: Poll Submission

### ISSUE THREAD

**Issue by Jordan-Boulton1** [Jordan-Boulton1/agile-project-1#3]
In order to **provide feedback anonymously**, as a **user**, I can **choose to hide my identity in the poll**

**Acceptance Criteria:**

- Acceptance Criteria 1: Option should be available as a checkbox.
- Acceptance Criteria 2: The default value of the checkbox should be "checked"
- Acceptance Criteria 3: The option should next to the submit button.
- Acceptance Criteria 4: After un-checking the checkbox, a warning should display, prompting a message that states the submission will **NOT** be anonymous.

# Tasks:
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and show the name of the submitter.
- [ ] Create a new field in the model to track the user name.
- [ ] Update controller function.
- [ ] Test functionality

**Comment by Jordan-Boulton1** [comment]
This is completed
